# Generated by Django 4.2.23 on 2025-07-01 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roastery", models.CharField(max_length=100)),
                (
                    "roast_level",
                    models.CharField(max_length=15, verbose_name="roast level"),
                ),
                ("origin", models.CharField(max_length=50)),
                ("process", models.CharField(max_length=25)),
                ("producer", models.CharField(max_length=50)),
                ("notes", models.CharField(max_length=100)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
    ]
