# Generated by Django 4.2.23 on 2025-07-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "roast_level",
                    models.CharField(
                        choices=[
                            ("L", "Light"),
                            ("LM", "Light-Medium"),
                            ("M", "Medium"),
                            ("MD", "Medium-Dark"),
                            ("D", "Dark"),
                        ],
                        default="M",
                        max_length=2,
                    ),
                ),
                (
                    "origin_type",
                    models.CharField(
                        choices=[("B", "Blend"), ("SO", "Single origin")],
                        default="B",
                        max_length=2,
                    ),
                ),
                ("origin", models.CharField(max_length=50)),
                (
                    "process",
                    models.CharField(
                        choices=[
                            ("W", "Washed"),
                            ("N", "Natural"),
                            ("H", "Honey"),
                            ("CF", "Cross fermented"),
                        ],
                        default="W",
                        max_length=2,
                    ),
                ),
                ("producer", models.CharField(max_length=50)),
                ("notes", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="beans/images/"),
                ),
            ],
        ),
    ]
