# Generated by Django 4.2.23 on 2025-07-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roaster", "0001_initial"),
        ("beans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="roaster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beans",
                to="roaster.roaster",
            ),
        ),
    ]
