# Generated by Django 4.2.23 on 2025-07-01 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bean",
            name="origin_type",
            field=models.CharField(
                choices=[("B", "Blend"), ("SO", "Single origin")],
                default="B",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(
                choices=[
                    ("W", "Washed"),
                    ("H", "Honey"),
                    ("N", "Natural"),
                    ("CF", "Cross fermented"),
                ],
                default="W",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("D", "Dark"),
                    ("M", "Medium"),
                    ("L", "Light"),
                    ("LM", "Light-Medium"),
                    ("MD", "Medium-Dark"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roastery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="beans.roaster"
            ),
        ),
    ]
