# Generated by Django 4.2.23 on 2025-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0002_roaster_bean_origin_type_alter_bean_process_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="origin_type",
            field=models.CharField(
                choices=[("SO", "Single origin"), ("B", "Blend")],
                default="B",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(
                choices=[
                    ("W", "Washed"),
                    ("CF", "Cross fermented"),
                    ("H", "Honey"),
                    ("N", "Natural"),
                ],
                default="W",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("M", "Medium"),
                    ("L", "Light"),
                    ("MD", "Medium-Dark"),
                    ("LM", "Light-Medium"),
                    ("D", "Dark"),
                ],
                default="M",
                max_length=2,
            ),
        ),
    ]
