# Generated by Django 4.2.23 on 2025-07-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("beans", "0003_alter_bean_origin_type_alter_bean_process_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bean",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="roaster",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="roaster",
            name="state",
        ),
        migrations.AddField(
            model_name="roaster",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
            ),
        ),
        migrations.AddField(
            model_name="roaster",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(
                choices=[
                    ("W", "Washed"),
                    ("H", "Honey"),
                    ("CF", "Cross fermented"),
                    ("N", "Natural"),
                ],
                default="W",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("M", "Medium"),
                    ("MD", "Medium-Dark"),
                    ("D", "Dark"),
                    ("LM", "Light-Medium"),
                    ("L", "Light"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.city",
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="country",
            field=models.ForeignKey(
                default="United States",
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.country",
            ),
        ),
    ]
