# Generated by Django 4.2.23 on 2025-07-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("beans", "0004_remove_bean_rating_remove_roaster_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("D", "Dark"),
                    ("L", "Light"),
                    ("M", "Medium"),
                    ("MD", "Medium-Dark"),
                    ("LM", "Light-Medium"),
                ],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cities_light.region",
            ),
        ),
    ]
