# Generated by Django 4.2.23 on 2025-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0006_alter_bean_process_alter_bean_roast_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bean",
            old_name="roastery",
            new_name="roaster",
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(
                choices=[
                    ("H", "Honey"),
                    ("CF", "Cross fermented"),
                    ("W", "Washed"),
                    ("N", "Natural"),
                ],
                default="W",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("MD", "Medium-Dark"),
                    ("LM", "Light-Medium"),
                    ("M", "Medium"),
                    ("L", "Light"),
                    ("D", "Dark"),
                ],
                default="M",
                max_length=2,
            ),
        ),
    ]
