# Generated by Django 4.2.23 on 2025-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0007_rename_roastery_bean_roaster_alter_bean_process_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roaster",
            name="city",
        ),
        migrations.RemoveField(
            model_name="roaster",
            name="country",
        ),
        migrations.RemoveField(
            model_name="roaster",
            name="region",
        ),
        migrations.AlterField(
            model_name="bean",
            name="origin_type",
            field=models.CharField(
                choices=[("B", "Blend"), ("SO", "Single origin")],
                default="B",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="process",
            field=models.CharField(
                choices=[
                    ("W", "Washed"),
                    ("N", "Natural"),
                    ("H", "Honey"),
                    ("CF", "Cross fermented"),
                ],
                default="W",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roast_level",
            field=models.CharField(
                choices=[
                    ("L", "Light"),
                    ("LM", "Light-Medium"),
                    ("M", "Medium"),
                    ("MD", "Medium-Dark"),
                    ("D", "Dark"),
                ],
                default="M",
                max_length=2,
            ),
        ),
    ]
