# Generated by Django 4.2.23 on 2025-07-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roaster", "0001_initial"),
        ("beans", "0008_remove_roaster_city_remove_roaster_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bean",
            name="roaster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="roaster.roaster"
            ),
        ),
        migrations.DeleteModel(
            name="Roaster",
        ),
    ]
