# Generated by Django 4.2.23 on 2025-07-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roaster", "0001_initial"),
        ("beans", "0009_alter_bean_roaster_delete_roaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="bean",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="beans/images/"),
        ),
        migrations.AlterField(
            model_name="bean",
            name="roaster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beans",
                to="roaster.roaster",
            ),
        ),
    ]
