# Generated by Django 4.2.23 on 2025-07-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("roaster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roaster",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cities_light.country"
            ),
        ),
    ]
